export const ResponseMessage = {
    AUTHENTICATION_FAILED: "Authentication failed",
    INTERNAL_SERVER_ERROR: "Internal server error!",
    USER_CREATED: "You've successfully registered.",
    // USER_CREATED: "You've successfully registered. We've sent you a verification email.",
    SOMETHING_WENT_WRONG: "Something went wrong!",
    USER_NOT_CREATED: "User not created!",
    USER_ALREADY_CREATED: "User already created!",
    USER_LOGGED_IN: "User logged in.",
    INVALID_CREDENTIALS: "Invalid Credentials!",
    ACCOUNT_IS_INACTIVE: "Account inactive.",
    YOUR_ACCOUNT_NOT_VERIFIED: "Your account not verified!",
    USER_NOT_FOUND: "User not found!",
    ALL_FIELDS_REQUIRED: "All fields are required!",
    ADMIN_LOGGED_IN: "Admin logged in.",
    ADMIN_NOT_FOUND: "Admin not found!",
    USER_ACTIVATED: "User Activated",
    USER_IN_ACTIVATED: "User In-Activated",
    TOKEN_NOT_VALID: "Token not valid!",
    ACCOUNT_DEACTIVATED: "Account deactivated!",
    OLD_PASSWORD_INVALID: "Old password invalid!",
    OLD_AND_NEW_PASSWORD_SAME: "Old and new password can not be same!",
    PASSWORD_CHANGED: "Password changed successfully.",
    RESET_PASSWORD_ERROR: "Failed to reset password!",
    ADMIN_NOT_EXIST: "Admin not found!",
    USER_FETCHED: "User fetched successfully.",
    RESET_PASSWORD_MAIL: "Reset password OTP has been sent to your email",
    INVALID_OTP: "Invalid otp!",
    RESET_PASSWORD: "Password reset successfully.",
    PASSWORD_NOT_MATCH: "Password not match!",
    OLD_NEW_PASSWORD_ARE_MATCH: "Old and new password are match!",
    VERIFICATION_COMPLETED: "Verification complete.",
    OLD_NEW_PASSWORD_REQUIRED: "Old and new Password required!",
    CHAT_CREATED: "Chat created.",
    CHAT_NOT_CREATED: "Chat not created!",
    MESSAGE_SEND: "Message send.",
    MESSAGE_FETCHED: "Message fetched."
}